FROM node:22-alpine
RUN apk update && apk upgrade --no-cache
WORKDIR /app

COPY package*.json ./
RUN npm install

EXPOSE 4200 9229

CMD ["npx", "nodemon", "--config", "nodemon.docker.json", "--legacy-watch"]
